name: Generate contribution snake

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake_dark.svg?color_snake=%237aa2f7&color_dots=%2330363d,%230e4429,%23006d32,%2326a641,%2339d353
            assets/snake_light.svg?color_snake=%233b5bdb&color_dots=%23ebedf0,%239be9a8,%2340c463,%2330a14e,%23216e39

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update contribution snake [skip ci]"
          file_pattern: assets/snake_dark.svg assets/snake_light.svg
